# Generated by Django 5.0.1 on 2024-02-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_endpoint_relative_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
