# Generated by Django 5.0.1 on 2024-02-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_application_id_alter_endpoint_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='request_type',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=10),
        ),
    ]
