# Generated by Django 5.0.1 on 2024-02-17 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_application_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='schema',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
