# Generated by Django 5.0.1 on 2024-02-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_endpoint_schema_alter_application_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='response',
            field=models.TextField(blank=True),
        ),
    ]
