# Generated by Django 5.0.1 on 2024-02-18 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_endpoint_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='application.application'),
        ),
    ]
